### ISSUE TITLE
fix fawe compatibility!!!

### ISSUE THREAD

**Issue by FreedomForeverMC** [InsightsPlugin/Insights#102]
no work for fawe!!! (fastasyncworldedit)

**Comment by FreedomForeverMC** [comment]
worldedit extension btw

**Comment by FrankHeijden** [comment]
Thanks for reporting! Someone already made an issue on the InsightsWorldEditExtension github: https://github.com/InsightsPlugin/InsightsWorldEditExtension/issues/6

I am looking to fix this issue in the coming week; I will close this issue (as its already on the above one to avoid duplicate issues)

Thanks!
