### ISSUE TITLE
Error with plotsquared

### ISSUE THREAD

**Issue by makemp1997** [InsightsPlugin/Insights#103]
Hello,
I have got the following error when using the plotsquared addon: https://hastebin.com/doxawasifa.properties

Sadly no result cam from /scregion scan thou

I have also the following data which might help you:

- mc version: Paper-626 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
- Insight version:  6.3.1
- Plotsquared version: 4.4.495

Greetins,

makemp1997
aka mapemp2014

**Comment by FrankHeijden** [comment]
Heya, thanks for the report! Unfortunately, there is nothing much I can do as Insights' addons will only support the latest versions of the plugins they integrate with. For PlotSquared, this is v5, which can be downloaded from here: https://www.spigotmc.org/resources/plotsquared-v5.77506/

Thanks!
