### ISSUE TITLE
Limit Issues

### ISSUE THREAD

**Issue by sphings79** [InsightsPlugin/Insights#121]
I'm on latest paper 1.17.1 and latest plugin version and latest fawe.

I've created a group of Armor Stands and Item Frames:
`limit:
  name: "Bilderrahmen & Rüstungsständer"
  type: "GROUP"
  bypass-permission: "insights.bypass.limit.iframes_ast"
  limit: 10
  materials:
    - "ITEM_FRAME"
    - "GLOW_ITEM_FRAME"
    - "ARMOR_STAND"
  settings:
    enabled-worlds:
      whitelist: false
      worlds: []
    enabled-addons:
      whitelist: false
      addons: []
    disallow-placement-outside-region: false`

Armor Stands will be removed if over 10.
But i can place item frames over the limit.

Also I'm not able to place an armor stand in the next chunk. 2 chunks later, there is no problem zo place 10 armor stands again.

There are no console errors.

**Comment by FrankHeijden** [comment]
`ITEM_FRAME`, `GLOW_ITEM_FRAME` and `ARMOR_STAND` are entities, so you can't place them in the `materials:` section, instead you should use the `entities:` section :)

P.S. You can use triple \` to format your code, like this:
\`\`\`yaml
hello:
&nbsp;&nbsp;world: "!"
\`\`\`

Then it will look like this:
```yaml
hello:
  world: "!"
```
