### ISSUE TITLE
Insights checks are done before build checks

### ISSUE THREAD

**Issue by crafter23456** [InsightsPlugin/Insights#124]
1. ![image](https://user-images.githubusercontent.com/64259198/128511722-fd69537b-450b-466a-a44f-9bd79f747df6.png)
Is it possible to turn off the message & actionbar that the plot get scanned, should be only for owner
2. Limit is for example 10k per plot, I have on one side 12k blocks placed per command & on the other plot side of the merge I cant place more so I think the limit should be doubled
3. The redstone limit message appears even if the user isnt trusted.

**Comment by FrankHeijden** [comment]
Point 1 & 3 can be configured with the options provided by #125, which will allow the ability to customize the eventpriority of certain events. Setting the priority higher will result in that other plugins can do their checks before Insights.

Point 2 is actually similar to #100, which is about making limits proportional to the region size.
