### ISSUE TITLE
Liquids are ignored and can't be limited

### ISSUE THREAD

**Issue by UDPSendToFailed** [InsightsPlugin/Insights#173]
Whenever I add LAVA or WATER to the configuration files, the limitation isn't enforced, the players are still able to place an infinite number of lava or water source blocks.

Versions:

- Insights 6.12.1-SNAPSHOT
- GriefPreventionAddon 2.1.0
- GriefPrevention 16.18

**Comment by FrankHeijden** [comment]
Will check this out in 1-2 weeks from now, currently enjoying a holiday ☀️
