### ISSUE TITLE
Suggestion about performing a blocking I/O operation on the main thread

### ISSUE THREAD

**Issue by FunkyNico** [InsightsPlugin/Insights#176]
Hello, I have found this suggestion from another spigot plugin called [Lagmonitor ](https://github.com/games647/LagMonitor): Make stop the plugin from doing a blocking I/O operation on the main thread because this could affect the server performance, the thread pauses until it gets the response. Such operations should be performed asynchronous from the main thread. Besides gameplay performance it could also improve startup time.

Insights Plugin Version: 6.12.1 / Server: Purpur-1762 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 39e30d6 on HEAD).

Log: https://logs.apexminecrafthosting.com/tOylXw3

Thanks :D

**Comment by FrankHeijden** [comment]
The IO operation Insights does here is loading addons, this only happens at startup and it needs to happen on the main thread ^^

Lagmonitor is probably complaining because it is a scheduled task, is there a way to let this plugin ignore this operation? If not, maybe suggest it to the developer
