### ISSUE TITLE
Insights bentobox oneblock nether and end issue

### ISSUE THREAD

**Issue by VacBanYT** [InsightsPlugin/Insights#178]
Hello, I have problem with Insights limits not working in oneblock_world_nether and oneblock_world_the_end
/scanregion also does not work in this worlds however, scans and limits work perfectly fine in oneblock_world.
I am using Paper 1.19.2 with latest Insighits with BentoBox addon to run limits on my OneBlock server.
Those are my error logs when a player tries to place the restricted block in these two worlds:
[message (2).txt](https://github.com/InsightsPlugin/Insights/files/9401566/message.2.txt)
.
Versions:
- BentoBox-1.20.1.jar
- Insights-6.12.2.jar
- BentoBoxAddon-2.0.1.jar

**Comment by VacBanYT** [comment]
![image](https://user-images.githubusercontent.com/111865770/186131891-bb000076-45c1-4066-ab80-34f8eca64712.png)
![image](https://user-images.githubusercontent.com/111865770/186131924-edd24045-0917-4837-814a-428520d6753c.png)

**Comment by FrankHeijden** [comment]
Seems like BentoBox returns a wrong BoundingBox for the nether world. The world only goes up to Y256, but BentoBox returns Y320. Bandaid fix in v2.1.0: https://github.com/InsightsPlugin/BentoBoxAddon/releases

**Comment by FrankHeijden** [comment]
Also created an issue for it on BentoBox: https://github.com/BentoBoxWorld/BentoBox/issues/2014
