### ISSUE TITLE
Incompability with RoseStacker (API missing)

### ISSUE THREAD

**Issue by LuluxClient** [InsightsPlugin/Insights#201]
Hey I'm trying to add support to rosestacker that has an option where you could silktouch spawners but one of their updates broke something where insights won't recognize the spawner being broken. This is causing the chunk being 'full of spawners' when it's not. To fix it we will need some API additions so we could add support to Insights to RoseStacker about " able to arbitrarily increment or decrement the count of blocks that exist"

Version: 1.19.4

Insights: 6.15.0

**Comment by FrankHeijden** [comment]
Yes that's possible using the Insights API:

You can get an instance of Insights using `InsightsPlugin.getInstance()`, and then there are a lot of methods you may use from there: https://github.com/InsightsPlugin/Insights/blob/master/Insights-API/src/main/java/dev/frankheijden/insights/api/InsightsMain.java

The one that is probably of interest to you is `getWorldStorage()`, on which you can call `getWorld(UUID)`, to get the particular world's storage instance, then `get(long)`, where `long` is the chunk key (computable with the utility ChunkUtils: https://github.com/InsightsPlugin/Insights/blob/master/Insights-API/src/main/java/dev/frankheijden/insights/api/utils/ChunkUtils.java). Then you can modify the world's storage with https://github.com/InsightsPlugin/Insights/blob/14e1382fe9b7198e3256015e9c6f003c3d73c074/Insights-API/src/main/java/dev/frankheijden/insights/api/concurrent/storage/Storage.java#L59C5-L59C50

ScanObject is just a wrapper for materials/entities which provide static methods to create instances.

Hope this helps!

**Comment by LuluxClient** [comment]
> Yes that's possible using the Insights API:
> 
> You can get an instance of Insights using `InsightsPlugin.getInstance()`, and then there are a lot of methods you may use from there: https://github.com/InsightsPlugin/Insights/blob/master/Insights-API/src/main/java/dev/frankheijden/insights/api/InsightsMain.java
> 
> The one that is probably of interest to you is `getWorldStorage()`, on which you can call `getWorld(UUID)`, to get the particular world's storage instance, then `get(long)`, where `long` is the chunk key (computable with the utility ChunkUtils: https://github.com/InsightsPlugin/Insights/blob/master/Insights-API/src/main/java/dev/frankheijden/insights/api/utils/ChunkUtils.java). Then you can modify the world's storage with https://github.com/InsightsPlugin/Insights/blob/14e1382fe9b7198e3256015e9c6f003c3d73c074/Insights-API/src/main/java/dev/frankheijden/insights/api/concurrent/storage/Storage.java#L59C5-L59C50
> 
> ScanObject is just a wrapper for materials/entities which provide static methods to create instances.
> 
> Hope this helps!

Thank you !!! <3 We'll try soon !

**Comment by LuluxClient** [comment]
Fixed, thanks <3
