### ISSUE TITLE
Bypass limit with dispensers & water (LAG MACHINE)

### ISSUE THREAD

**Issue by LuluxClient** [InsightsPlugin/Insights#204]
You can simply bypass the chunk limit of armor stands for example with a dispenser and you can lag out a server in this way same thing with water, simple make a water stream to one chunk to another and you will be able to bypass the limit

Example: https://gyazo.com/95d41c8908ad9aed1256192ae7df8c57

**Comment by FrankHeijden** [comment]
Insights doesn't support moving entities, so you should use another plugin if you enabled armorstands to be moved by water. Farmlimiter might be useful here, or similar.
