### ISSUE TITLE
Blocks broken by water won't be recognized.

### ISSUE THREAD

**Issue by Nononitas** [InsightsPlugin/Insights#206]
For example, if you have a limit set for redstone wire, the limit won't decrease if the redstone is broken by water.

**Comment by FrankHeijden** [comment]
You can remove this option from the default config to fix this, these events are disabled by default as they might get called very often and introduce lag:
```
  disabled-listeners:
    - "BlockFromToEvent"
```

Just comment it out like so:
```
  disabled-listeners:
    #- "BlockFromToEvent"
```

**Comment by Nononitas** [comment]
I see thank you for clarifying
