### ISSUE TITLE
1.20.4 Insights do not work + Console spam

### ISSUE THREAD

**Issue by Yertled** [InsightsPlugin/Insights#213]
Every time people place a block that's in the filtered list, the console spams with errors.
https://mclo.gs/uCxd84A

Version: Insights-6.17.0.jar
Pufferfish+ version git-PufferfishPlus-33 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 94fa469 on HEAD)

**Comment by Yertled** [comment]
The limits seems to be respected, but no bossbar is shown and its spamming console

**Comment by Yertled** [comment]
No insights command seem to work either.
/insights:scan 10 custom armor_stand (Nothing shows in chat about the scan)
https://mclo.gs/t5WkLys

**Comment by FrankHeijden** [comment]
Try v6.17.1, https://github.com/InsightsPlugin/Insights/actions/runs/7438882029

Can't publish on modrinth yet as for some reason cannot select Paper/Purpur as the loader lol

**Comment by Yertled** [comment]
> Try v6.17.1, https://github.com/InsightsPlugin/Insights/actions/runs/7438882029
> 
> Published on modrinth as loader "Fabric" as for some reason cannot select Paper/Purpur as the loader lol https://modrinth.com/plugin/insights/version/6.17.1

Works fine with bossbar and notifications in chat. Thank you so much.

**Comment by Yertled** [comment]
> > Try v6.17.1, https://github.com/InsightsPlugin/Insights/actions/runs/7438882029
> > Published on modrinth as loader "Fabric" as for some reason cannot select Paper/Purpur as the loader lol https://modrinth.com/plugin/insights/version/6.17.1
> 
> Works fine with bossbar and notifications in chat. Thank you so much.

Sorry to re-open, but all bossbar messages has "test" above it now 😋
![image](https://github.com/InsightsPlugin/Insights/assets/12172847/a34613dc-dc21-413d-8aec-44ed927343e0)

**Comment by FrankHeijden** [comment]
can you show your config

**Comment by Yertled** [comment]
> can you show your config

https://mclo.gs/aYny9bA

**Comment by FrankHeijden** [comment]
i mean messages.yml

**Comment by Yertled** [comment]
> i mean messages.yml

Found the issue... Sorry to bother you! "test" was in the messages.yml
