### ISSUE TITLE
Per World Limiting

### ISSUE THREAD

**Issue by NolanMC** [InsightsPlugin/Insights#26]
I think that this plugin could be made more versatile by enabling a way to have limits that are per world. This would mean that if you have the plugin enabled in multiple worlds, that you could have different settings in each world. I am not much of a developer and don't have much to offer into "how" this should be implemented, but would donate to see such a feature added.

My personal use case for such a feature would be so that I could have different limits enforced for Skyblock Islands, and for the Nether/End worlds. When this plugin is used in combination with the Bento addon, the limits are applied to islands in the Bento world, and by chunk in every other world. This makes configuring useful limits very hard in this scenario very difficult.

I realize how busy you may possibly be, and I appreciate the time and effort put into this plugin, thank you.

**Comment by FrankHeijden** [comment]
Implemented in v6! (closing issue to keep issues up2date with stuff I still need to do)
