### ISSUE TITLE
getAmountInChunk error

### ISSUE THREAD

**Issue by makemp1997** [InsightsPlugin/Insights#28]
Good afternoon ,

I got an issue that /autoscan doesn't' seems to work for me, for example  /autoscan limit REDSTONE_WIRE.
Also I got the following error that is spamming my console: https://hastebin.com/yacoxiyepo.bash

For your info:
Server / gamemode : Creative
Plugins : ![creative plugins](https://user-images.githubusercontent.com/22965328/89900881-9b22d880-dbe4-11ea-817b-75206010a67e.png)
Version: ![Server version](https://user-images.githubusercontent.com/22965328/89904016-b2fc5b80-dbe8-11ea-9294-5bfb7ad3dfb7.png)

Also how can I enable the bossbar, is seems that doesn't show.

Greetinngs,

makemp2014
aka makemp1997

**Comment by FrankHeijden** [comment]
Hey, thanks for reporting! I fixed the error, will publish the update on spigot later this day, will also include another feature in this update.

What do you mean by showing the bossbar? If you want the bossbar during block placements/removals, you should give yourself the permission `insights.check.realtime` :)

**Comment by FrankHeijden** [comment]
Released v5.4.0!
