### ISSUE TITLE
Farmland limit cause Hoe Duplication

### ISSUE THREAD

**Issue by ravielze** [InsightsPlugin/Insights#31]
There is hoe duplication when farmland has a limit. For further explanation please see this video.
https://user-images.githubusercontent.com/25381483/104084870-c0903d00-527d-11eb-9d5d-812b5cb3dffb.mp4

**Comment by FrankHeijden** [comment]
Hi!

Thanks for reporting, this has been fixed in the latest version of Insights, v5.7.0!

**Comment by ravielze** [comment]
Thanks
